# Generated by Django 5.2 on 2025-11-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Quiz_Details", "0002_question_level_userprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="passed_level1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="passed_level2",
            field=models.BooleanField(default=False),
        ),
    ]
